irriz-jayy/Moringa-student-application-portal

- client/src/App.css
- client/src/App.js
I Have removed the default logo on APP.js
> first changes, editing css

- client/src/App.js
Reverts irriz-jayy/Moringa-student-application-portal#15
> Revert "code cleanup"

- client/src/App.js
Changed App.js to arrange the routes and NavBar in the container
> arranged App.js for routes and NavBar

- client/src/App.css
- client/src/components/NavBar.css
- client/src/components/Navbar.jsx
- client/src/containers/LandingPage.css
Added styling to NavBar.
Edited LandingPage styling to account for NavBar.
> added NavBar styling

- client/src/components/Form.css
- client/src/components/Login.jsx
- client/src/components/Signup.jsx
Renamed Signup.css to Form.css.
Added styling to Login component using Form.css.
> added styling to Login component

- client/src/components/Form.css
- client/src/containers/LandingPage.js
Added responsiveness to the Form.css in terms of font-size and padding.
> added responsivesness to Form.css

- .byebug_history
- Gemfile
- Gemfile.lock
- app/controllers/applicants_controller.rb
- app/controllers/application_controller.rb
- app/controllers/applications_controller.rb
- app/controllers/courses_controller.rb
- app/controllers/sessions_controller.rb
- app/models/applicant.rb
- app/models/application.rb
- app/models/course.rb
- app/serializers/applicant_serializer.rb
- app/serializers/application_serializer.rb
- app/serializers/course_serializer.rb
- client/package.json
- config.ru
- config/application.rb
- config/initializers/cors.rb
- config/routes.rb
- db/schema.rb
Repaired the backend and configured it together with the frontend.
> backend repair and configuration

- client/src/App.js
- client/src/components/Login.jsx
- client/src/components/Navbar.jsx
Configured frontend to work with a proxy.
Changed logo image src to an external link.
> configured frontend to work with proxy

- client/src/components/Signup.jsx
signup component post functionalities
> signup post functionalities

- app/controllers/applicants_controller.rb
- app/controllers/application_controller.rb
- app/controllers/applications_controller.rb
- app/controllers/courses_controller.rb
- app/controllers/sessions_controller.rb
- app/models/applicant.rb
- app/serializers/applicant_serializer.rb
- app/serializers/application_serializer.rb
- app/serializers/course_serializer.rb
- config/routes.rb
- db/migrate/20230327140757_create_applicants.rb
- db/schema.rb
- db/seeds.rb
- node_modules/.package-lock.json
Edited and made changes on validation and seeded data, also added authentication
> validations and seeding changes

- app/controllers/applicants_controller.rb
- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- client/src/App.js
- client/src/components/Login.jsx
- config/routes.rb
- db/migrate/20230327140852_create_applications.rb
- db/schema.rb
Updated database schema to remove t.belongs_to attributes.
Updated the SessionsController to follow conventions with POST /login to #create that logs in the user, and DELETE /logout to #destroy that logs out the user.
Updated the ApplicantsController to have GET /me point to #show, which fetches the currently logged-in user using the sessions[:applicant_id].
Updated App component and Login component to log in the user and keep the user logged in, even on refreshing the page.
> updated Login flow for both backend and frontend

- app/controllers/applicants_controller.rb
- app/controllers/sessions_controller.rb
- client/src/App.js
- client/src/components/Login.jsx
- client/src/components/Navbar.jsx
- client/src/components/Signup.jsx
- client/src/containers/LandingPage.js
NavBar component changes if a user is logged in.
LandingPage component displays the current user's first name in a greeting.
> created user logout flow and frontend display using current user

- client/src/components/Card.css
- client/src/components/CourseCard.jsx
The Card component can now be used on the AllCourses component or the MyApplications component and the styling can be updated as needed by using "course-card" or "application-card" respectively.
> updated styling for ApplicationCard component

- app/models/applicant.rb
- client/src/components/Signup.jsx
Updated the :over_18 validation in the applicant.rb to calculate the exact age using the full date in order to determine the age of the applicant.
Added the password field to the signup form.
> updated Signup validation to use exact age

- app/models/applicant.rb
- db/seeds.rb
Refactored Applicant.rb for validations.
Changed date_of_birth attribute from integers to strings.
> edited seed data date_of_birth from integers to strings

- Gemfile
- Gemfile.lock
- app/controllers/applications_controller.rb
- client/src/App.css
- client/src/App.js
- client/src/components/Application.jsx
- client/src/components/CourseCard.jsx
- client/src/components/CourseDetails.jsx
- client/src/components/MyApplications.jsx
- client/src/components/MyApplicationsCard.jsx
- client/src/components/Navbar.jsx
- client/src/components/Signup.jsx
- client/src/components/UpdateApplication.jsx
- client/src/containers/AllCourses.js
Added Applications and MyApplications components.
Added a search bar to the AllCourses component for filtering courses.
Added functionality to create a new application.
Waiting on backend for update and delete functionality.
> application module and functionalities

- client/src/components/Application.jsx
- client/src/components/Form.css
- client/src/components/MyApplications.jsx
- client/src/components/MyApplicationsCard.jsx
- client/src/components/UpdateApplication.jsx
- client/src/containers/LandingPage.css
- client/src/containers/LandingPage.js
- db/seeds.rb
Added applications data as comments, as the seeding through the seed file is not working.
Styled the MyApplications and MyApplicationsCard components.
Added styling to UpdateApplication component.
Changed the user greeting for better visibility.
Added styling to the Application form. Also changed the newApplication data such that, once the form is submitted, it takes the course and current user ids and sets them as the values in the body of the request. It also defaults the value of the status attribute of the newApplication object from "Applying" to "Submitted" once the form is submitted.
> Styling Application forms and refactoring form requests

- client/src/components/CourseCard.jsx
- client/src/components/CourseDetails.css
- client/src/components/CourseDetails.jsx
- client/src/components/MyApplicationsCard.jsx
- db/seeds.rb
Added styling to the CourseDetails component.
Updated the start_date display format into a string.
Updated the applications' seed data.
> added styling to CourseDetails component

- app/controllers/applications_controller.rb
- client/src/App.js
- client/src/components/UpdateApplication.jsx
- client/src/containers/AllCourses.js
- db/seeds.rb
Added the PATCH /applications request to UpdateApplication. The user is now able to updated an existing application.
> added PATCH request to UpdateApplication form

- client/src/components/CourseDetails.css
- client/src/components/CourseDetails.jsx
- client/src/containers/AllCourses.css
- client/src/containers/AllCourses.js
- db/seeds.rb
Updated seed data for missing images for various courses and on some of the course data,
Added styling to the searchbar element in the AllCourses component by moving it to the header.
Added condition for Call to Action depending on the course status. The Apply now will only appear if the course's status is "Intake ongoing". The apply now button will also be disabled. 
Updated the header image styling in the CourseDetails component.
> updated styling for CourseDetails and seed data

- client/src/App.css
- client/src/components/Application.jsx
- client/src/components/CourseDetails.jsx
- client/src/components/LoadingScreen.jsx
- client/src/components/MyApplications.jsx
- client/src/components/MyApplicationsCard.jsx
- client/src/components/UpdateApplication.jsx
- client/src/containers/AllCourses.js
Created LoadingScreen component.
Added the LoadingScreen component to AllCourses, CourseDetails, MyApplications, Application, and UpdateApplication components.
> added LoadingScreen component
